### TEST GET / WEBSITE 
GET http://localhost:5003

### TEST GET /dashboard WEBSITE 
GET http://localhost:5003/dashboard

### DATA ENDPOINT GET http://localhost:5003/api/data

### DATA ENDPOINT FOR ADDING A USER 
POST http://localhost:5003/api/data 
Content-Type: application/json

{
"name": "john"
}

### DELETE END POINT

DELETE http://localhost:5003/api/data